# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20170416_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='pub_date',
        ),
    ]
