# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_auto_20170417_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='goodreads_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_filepath',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
